### ISSUE TITLE
The top corners of scale bars are rounded

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [ome/omero-iviewer#259]
The top corners of scale bars are rounded with dark background.

![3950552515-Image003](https://user-images.githubusercontent.com/6400352/55480139-80674980-5617-11e9-9352-4ed0926706e6.png)

The following seems to work well.
```css
.ol-scale-line.ol-unselectable.ol-control {
    border-radius: 0;
}
```
